[project]
name = "fastapi-alchemy"
version = "0.5"
description = "A REST Framework for FastAPI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alembic>=1.15.2",
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "orjson>=3.10.18",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
    "sqlalchemy[asyncio]>=2.0.41",
]

[dependency-groups]
dev = [
    "ipython>=8.36.0",
    "mkdocs-material>=9.6.14",
    "pdbpp>=0.11.6",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "ruff>=0.11.10",
]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "--ignore=example-projects"

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
select = ["I"]
fixable = ["I"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.setuptools.packages.find]
where = ["."]
include = ["fastapi_alchemy"]

